function [fitresult, gof] = createFit(b2, f2)
%CREATEFIT(B2,F2)
%  Create a fit.
%
%  Data for 'gauss4' fit:
%      X Input : b2
%      Y Output: f2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Oct-2016 15:33:48


%% Fit: 'gauss4'.
[xData, yData] = prepareCurveData( b2, f2 );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [54690 51.051 14.734147844914 34585.8813436664 27.027 18.7032186222794 32534 -107.11 21.5307689533752 19972.6364121955 -7.007 27.6478045085227];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'gauss4' );
h = plot( fitresult, xData, yData );
legend( h, 'f2 vs. b2', 'gauss4', 'Location', 'NorthEast' );
% Label axes
xlabel b2
ylabel f2
grid on


